from datetime import timedelta
from sqlite3.dbapi2 import Cursor
from tkinter import*
from tkinter import messagebox as tkMessageBox, Tk, Label
import sqlite3 as sql
import locale
import datetime
import csv
import os
from openpyxl import Workbook
from typing import Union

p=Tk()
p.geometry("600x600")
p.title("NEFL KÜTÜPHANESİ")
p.configure(background="white")
foto=PhotoImage(file="NEFL_logo.png")
etiket=Label(p,image = foto)
etiket.pack(pady=125,padx=125)

def excel():
    conn = sql.connect("Big data.db")
    c = conn.cursor()
    c.execute("SELECT * FROM kayit")
    vtx = c.fetchall()
    with open('output.csv', 'w') as f:
        writer = csv.writer(f)
        writer.writerow(['ad', 'soyad', 'no', 'sinif', 'kitapadi', 'kitapno', 'yazar', 'tarih', 'alıştarihi'])
        writer.writerows((vtx))
    wb = Workbook()
    ws = wb.active
    with open('output.csv', 'r') as f:
        for row in csv.reader(f):
            ws.append(row)
    wb.save('liste.xlsx')
    os.remove('output.csv')
    os.startfile('liste.xlsx')
    conn.commit()
    conn.close()

def excelr():
    conn = sql.connect("Big data.db")
    d= conn.cursor()
    today=datetime.datetime.now()
    today=today.strftime("%Y/%m/%d")
    datavt = d.execute("SELECT * FROM kayit WHERE alıştarihi<='"+today+"'; ")
    with open('output.csv', 'w') as f:
        writer = csv.writer(f)
        writer.writerow(['ad', 'soyad', 'no', 'sinif','kitapadi','kitapno','yazar','tarih','alıştarihi'])
        writer.writerows("datavt")
    wb = Workbook()
    ws = wb.active
    with open('output.csv', 'r') as f:
        for row in csv.reader(f):
            ws.append(row)
    wb.save('liste2.xlsx')
    os.remove('output.csv')
    os.startfile('liste2.xlsx')
def kaydet():
    ad=(e1.get().title())
    soyad=(e2.get().title())
    no=(e3.get().title())
    sinif=e4.get()
    kitapadi=(e5.get().title())
    kitapno=e6.get()
    yazar=(e8.get().title())
    tarih=e7.get()
    db=sql.connect("Big data.db")
    vt=db.cursor()
    vt.execute("INSERT INTO kayit VALUES (?,?,?,?,?,?,?,?,?)",(ad,soyad,no,sinif,kitapadi,kitapno,yazar,tarih,altarih))
    db.commit()
    db.close()
    tkMessageBox.showinfo("KAYDEDİLDİ")

def ara():
    global arama,entryara
    arama=entryara.get()
    db=sql.connect("Big data.db")

    vt=db.cursor()
    vt.execute("SELECT * FROM kayit WHERE no=?",(arama,))
    data=vt.fetchall()
    for d in data:
        global ad,soyad,no,sinif,kitapadi,kitapno,yazar,tarih,altarih,labelad,labelsoyad,labelno,labelsinif,labelkitapadi,labelkitapno,labelyazar,labeltarih
        ad,soyad,no,sinif,kitapadi,kitapno,yazar,tarih,altarih=d
    if data:
        labelad.destroy()
        labelsoyad.destroy()
        labelno.destroy()
        labelsinif.destroy()
        labelkitapadi.destroy()
        labelkitapno.destroy()
        labelyazar.destroy()
        labeltarih.destroy()

        labelad=Label(text=(ad))
        labelad.place(relx=0.4,rely=0.3)
        labelsoyad=Label(text=(soyad))
        labelsoyad.place(relx=0.4,rely=0.35)
        labelno=Label(text=(no))
        labelno.place(relx=0.4,rely=0.4)
        labelsinif=Label(text=(sinif))
        labelsinif.place(relx=0.4,rely=0.45)
        labelkitapadi=Label(text=(kitapadi))
        labelkitapadi.place(relx=0.4,rely=0.5)
        labelkitapno=Label(text=(kitapno))
        labelkitapno.place(relx=0.4,rely=0.55)
        labelyazar=Label(text=(yazar))
        labelyazar.place(relx=0.4,rely=0.6)
        labeltarih=Label(text=(tarih))
        labeltarih.place(relx=0.4,rely=0.65)
    else:
        pass

labelad=Label(text="")
labelad.pack()
labelsoyad=Label(text="")
labelsoyad.pack()
labelno=Label(text="")
labelno.pack()
labelsinif=Label(text="")
labelsinif.pack()
labelkitapadi=Label(text="")
labelkitapadi.pack()
labelkitapno=Label(text="")
labelkitapno.pack()
labelyazar=Label(text="")
labelyazar.pack()
labeltarih=Label(text="")
labeltarih.pack()
def sil(arama, entryara):
  #global arama, entryara
  arama=entryara.get()
  db=sql.connect("Big data.db")
  vt=db.cursor()
  vt.execute("DELETE FROM kayit WHERE no=?",(arama,))
  db.commit()
  db.close()
  tkMessageBox.showinfo("TAMAM","kayıt silindi")

def ogrenciler():
    p.withdraw()
    global op,ek,lo1,es,ew,ez,ex,lo2,lo3,lo4,lo5,b1
    op=Tk()
    op.title("ÖĞRENCİ KAYIT")
    #op.configure(background="brown")
    op.geometry("600x600")
    ek=Entry(op)
    ek.place(relx=0.7,rely=0.15)
    es=Entry(op)
    es.place(relx=0.7,rely=0.25)
    ew=Entry(op)
    ew.place(relx=0.7,rely=0.35)
    ez=Entry(op)
    ez.place(relx=0.7,rely=0.45)
    ex=Entry(op)
    ex.place(relx=0.7,rely=0.55)
    ez=Entry(op)
    ez.place(relx=0.4,rely=0.7)

    lo1=Label(op,text="AD:")
    lo1.place(relx=0.2,rely=0.15)
    lo2=Label(op,text="SOYAD:")
    lo2.place(relx=0.2,rely=0.25)
    lo3=Label(op, text="SINIF:")
    lo3.place(relx=0.2,rely=0.35)
    lo4=Label(op, text="NO:")
    lo4.place(relx=0.2,rely=0.45)
    lo5=Label(op, text="MEZUN TARİHİ:")
    lo5.place(relx=0.2,rely=0.55)
    b1=Button(op,text="KAYDET",command=kayit)
    b1.place(relx=0.45,rely=0.6)
    b2=Button(op,text="    SİL    ",command=sildir)
    b2.place(relx=0.45,rely=0.8)
    b3=Button(op,text="    ARA    ",command=arat)
    b3.place(relx=0.45,rely=0.9)
    men=Menu(op)
    op.config(menu=men)
    mendosya = Menu(men, tearoff=0)
    men.add_cascade(label='Menü', menu=mendosya)
    mendosya.add_command(label="-> ANASAYFAYA DÖN", command=ogeri)
    mendosya.add_command(label="KİTAP KAYDET", command=chrysler)
    mendosya.add_command(label="MEZUN OLANLARI SİL", command=bentley)
    op.mainloop()

def kayit():
    ad=(ek.get().title())
    soyad=(es.get().title())
    sinif=(ew.get().title())
    no=ez.get()
    mezuntar=(ex.get().title())
    db = sql.connect("Big data.db")
    vt = db.cursor()
    vt.execute("INSERT INTO kişiler VALUES (?,?,?,?,?)",(ad,soyad,sinif,no,mezuntar))
    db.commit()
    db.close()
    tkMessageBox.showinfo("KAYDEDİLDİ")
def arat():
    global aratt,ez,ql,qk,qv,qy,qz
    aratt = ez.get()
    db = sql.connect("Big data.db")
    vt = db.cursor()
    vt.execute("SELECT * FROM kişiler WHERE no=?", (aratt,))
    databases = vt.fetchall()
    for w in databases:
        ad,soyad,sinif,no,mezuntar = w
    if databases:
        ql.destroy()
        qk.destroy()
        qy.destroy()
        qv.destroy()
        qz.destroy()

        ql = Label(op, text=ad)
        ql.place(relx=0.45, rely=0.1)
        qk = Label(op, text=soyad)
        qk.place(relx=0.45, rely=0.2)
        qy = Label(op, text=sinif)
        qy.place(relx=0.45, rely=0.3)
        qv=Label(op,text=no)
        qv.place(relx=0.45,rely=0.4)
        qz=Label(op,text=mezuntar)
        qz.place(relx=0.45,rely=0.5)

    else:
        pass


ql = Label(text="")
ql.pack()
qk = Label(text="")
qk.pack()
qy = Label(text="")
qy.pack()
qv = Label(text="")
qv.pack()
qz = Label(text="")
qz.pack()



def sildir():
    global aratt,ez
    aratt = ez.get()
    db = sql.connect("Big data.db")
    vt = db.cursor()
    vt.execute("DELETE FROM kişiler WHERE no=?", (aratt,))
    db.commit()
    db.close()
    tkMessageBox.showinfo("TAMAM", "kayıt silindi")
def chrysler():
    op.withdraw()
    global kp, ke1, ke2, ke3, ke4, kl1, kl2, kl3, kb1, kb2, kb3
    kp = Tk()
    kp.title("KİTAP KAYDET")
    kp.geometry("600x600")
    ke1 = Entry(kp)
    ke1.place(relx=0.6, rely=0.1)
    ke2 = Entry(kp)
    ke2.place(relx=0.6, rely=0.2)
    ke3 = Entry(kp)
    ke3.place(relx=0.6, rely=0.3)
    ke4 = Entry(kp)
    ke4.place(relx=0.35, rely=0.5)
    kl1 = Label(kp, text="KİTAP ADI:")
    kl1.place(relx=0.2, rely=0.1)
    kl2 = Label(kp, text="KİTAP NO:")
    kl2.place(relx=0.2, rely=0.2)
    kl3 = Label(kp, text="YAZAR:")
    kl3.place(relx=0.2, rely=0.3)
    kb1 = Button(kp, text="KAYDET", command=kitkayit)
    kb1.place(relx=0.4, rely=0.4)
    kb2 = Button(kp, text="     SİL     ", command=kitsil)
    kb2.place(relx=0.4, rely=0.6)
    kb3 = Button(kp, text="    ARA    ", command=kara)
    kb3.place(relx=0.4, rely=0.7)
    menuo = Menu(kp)
    kp.config(menu=menuo)
    mend = Menu(menuo, tearoff=0)
    menuo.add_cascade(label="Menü", menu=mend)
    mend.add_command(label="-> ANASAYFAYA GERİ DÖN", command=kgeri)
    mend.add_command(label="GERİ", command=chevrolet)
    kp.mainloop()

def bentley():
    op.withdraw()
    global yp, kk, xz, we, ab
    yp = Tk()
    yp.geometry("300x300")
    kk = Entry(yp)
    kk.place(relx=0.4, rely=0.2)
    xz = Label(yp, text="Mezun Tarihi")
    xz.place(relx=0.1, rely=0.2)
    we = Label(yp, text="Eminmisiniz!!!!!")
    we.place(relx=0.3, rely=0.3)
    ab = Button(yp, text="SİL!!!!!", command=msil)
    ab.place(relx=0.4, rely=0.45)
    menuu = Menu(yp)
    yp.config(menu=menuu)
    menudosyaa = Menu(menuu, tearoff=0)
    menuu.add_cascade(label='Menü', menu=menudosyaa)
    menudosyaa.add_command(label="-> ANASAYFAYA DÖN", command=mgeri)
    menudosyaa.add_command(label="GERİ", command=rollsroyce)
    yp.mainloop()

def chevrolet():
    kp.destroy()
    op.deiconify()

def rollsroyce():
    yp.destroy()
    op.deiconify()

def ogeri():
    op.destroy()
    p.deiconify()

def kitp():
    p.withdraw()
    global kp,ke1,ke2,ke3,ke4,kl1,kl2,kl3,kb1,kb2,kb3
    kp=Tk()
    kp.title("KİTAP KAYDET")
    kp.geometry("600x600")
    ke1=Entry(kp)
    ke1.place(relx=0.6,rely=0.1)
    ke2=Entry(kp)
    ke2.place(relx=0.6,rely=0.2)
    ke3=Entry(kp)
    ke3.place(relx=0.6,rely=0.3)
    ke4=Entry(kp)
    ke4.place(relx=0.35,rely=0.5)
    kl1=Label(kp,text="KİTAP ADI:")
    kl1.place(relx=0.2,rely=0.1)
    kl2=Label(kp,text="KİTAP NO:")
    kl2.place(relx=0.2,rely=0.2)
    kl3=Label(kp,text="YAZAR:")
    kl3.place(relx=0.2,rely=0.3)
    kb1=Button(kp,text="KAYDET",command=kitkayit)
    kb1.place(relx=0.4,rely=0.4)
    kb2=Button(kp,text="     SİL     ",command=kitsil)
    kb2.place(relx=0.4,rely=0.6)
    kb3=Button(kp,text="    ARA    ",command=kara)
    kb3.place(relx=0.4,rely=0.7)
    menuo=Menu(kp)
    kp.config(menu=menuo)
    mend=Menu(menuo,tearoff=0)
    menuo.add_cascade(label="Menü",menu=mend)
    mend.add_command(label="-> ANASAYFAYA GERİ DÖN",command=kgeri)
    mend.add_command(label="ÖĞRENCİ KAYDET", command=sakarya)
    mend.add_command(label="MEZUN OLANLARI SİL", command=sanfransisco)
    kp.mainloop()
def kitkayit():
    kitapadi=(ke1.get().title())
    kitapno=(ke2.get().title())
    yazar=(ke3.get().title())
    db=sql.connect("Big data.db")
    vt=db.cursor()
    vt.execute("INSERT INTO kitaplar VALUES(?,?,?)",(kitapadi,kitapno,yazar))
    db.commit()
    db.close()
    tkMessageBox.showinfo("KAYDEDİLDİ")
def kitsil():
    global araa,ke4
    araa = ke4.get()
    db = sql.connect("Big data.db")
    vt = db.cursor()
    vt.execute("DELETE FROM kitaplar WHERE kitapno=?", (araa,))
    db.commit()
    db.close()
    tkMessageBox.showinfo("TAMAM","kayıt silindi")

def kara():
    global aara,ke4,lka,lkn,ly,kitapadi,kitapno,yazar
    aara=ke4.get()
    db = sql.connect("Big data.db")
    vt = db.cursor()
    vt.execute("SELECT * FROM kitaplar WHERE kitno=?",(aara,))
    database=vt.fetchall()
    for x in database:
        kitad,kitno,theyazar=x
    if database:
        lka.destroy()
        lkn.destroy()
        ly.destroy()

        lka=Label(kp,text=kitad)
        lka.place(relx=0.7,rely=0.5)
        lkn=Label(kp,text=kitno)
        lkn.place(relx=0.7,rely=0.6)
        ly=Label(kp,text=theyazar)
        ly.place(relx=0.7,rely=0.7)
    else:
        pass

lka=Label(text="")
lka.pack()
lkn=Label(text="")
lkn.pack()
ly=Label(text="")
ly.pack()


def sakarya():
    kp.withdraw()
    global op, ek, lo1, es, ew, ez, ex, lo2, lo3, lo4, lo5, b1
    op = Tk()
    op.title("ÖĞRENCİ KAYIT")
    # op.configure(background="brown")
    op.geometry("600x600")
    ek = Entry(op)
    ek.place(relx=0.7, rely=0.15)
    es = Entry(op)
    es.place(relx=0.7, rely=0.25)
    ew = Entry(op)
    ew.place(relx=0.7, rely=0.35)
    ez = Entry(op)
    ez.place(relx=0.7, rely=0.45)
    ex = Entry(op)
    ex.place(relx=0.7, rely=0.55)

    lo1 = Label(op, text="AD:")
    lo1.place(relx=0.2, rely=0.15)
    lo2 = Label(op, text="SOYAD:")
    lo2.place(relx=0.2, rely=0.25)
    lo3 = Label(op, text="SINIF:")
    lo3.place(relx=0.2, rely=0.35)
    lo4 = Label(op, text="NO:")
    lo4.place(relx=0.2, rely=0.45)
    lo5 = Label(op, text="MEZUN TARİHİ:")
    lo5.place(relx=0.2, rely=0.55)
    b1 = Button(op, text="KAYDET", command=kayit)
    b1.place(relx=0.45, rely=0.6)
    men = Menu(op)
    op.config(menu=men)
    mendosya = Menu(men, tearoff=0)
    men.add_cascade(label='Menü', menu=mendosya)
    mendosya.add_command(label="-> ANASAYFAYA DÖN", command=ogeri)
    mendosya.add_command(label="GERİ", command=paris)
    op.mainloop()

def sanfransisco():
    kp.withdraw()
    global yp, kk, xz, we, ab
    yp = Tk()
    yp.geometry("300x300")
    kk = Entry(yp)
    kk.place(relx=0.4, rely=0.2)
    xz = Label(yp, text="Mezun Tarihi")
    xz.place(relx=0.1, rely=0.2)
    we = Label(yp, text="Eminmisiniz!!!!!")
    we.place(relx=0.3, rely=0.3)
    ab = Button(yp, text="SİL!!!!!", command=msil)
    ab.place(relx=0.4, rely=0.45)
    menuu = Menu(yp)
    yp.config(menu=menuu)
    menudosyaa = Menu(menuu, tearoff=0)
    menuu.add_cascade(label='Menü', menu=menudosyaa)
    menudosyaa.add_command(label="-> ANASAYFAYA DÖN", command=mgeri)
    menudosyaa.add_command(label="GERİ", command=lyon)
    yp.mainloop()

def paris():
    op.destroy()
    kp.deiconify()

def lyon():
    yp.destroy()
    kp.deiconify()

def kgeri():
    kp.destroy()
    p.deiconify()

def mezun():
    p.withdraw()
    global yp,kk,xz,we,ab
    yp=Tk()
    yp.geometry("300x300")
    kk=Entry(yp)
    kk.place(relx=0.4,rely=0.2)
    xz=Label(yp,text="Mezun Tarihi")
    xz.place(relx=0.1,rely=0.2)
    we=Label(yp,text="Eminmisiniz!!!!!")
    we.place(relx=0.3,rely=0.3)
    ab=Button(yp,text="SİL!!!!!",command=msil)
    ab.place(relx=0.4,rely=0.45)
    menuu=Menu(yp)
    yp.config(menu=menuu)
    menudosyaa = Menu(menuu, tearoff=0)
    menuu.add_cascade(label='Menü', menu=menudosyaa)
    menudosyaa.add_command(label="-> ANASAYFAYA DÖN", command=mgeri)
    menudosyaa.add_command(label="ÖĞRENCİ KAYDET",command=newyork)
    menudosyaa.add_command(label="KİTAP KAYDET", command=istanbul)
    yp.mainloop()
def msil():
    global ara, kk
    ara=kk.get()
    db=sql.connect("Big data.db")
    vt=db.cursor()
    vt.execute("DELETE FROM kişiler WHERE mezun_tarihi=?", (ara,))
    db.commit()
    db.close()
    tkMessageBox.showinfo("TAMAM", "kayıt silindi")
def newyork():
    yp.withdraw()
    global op, ek, lo1, es, ew, ez, ex, lo2, lo3, lo4, lo5, b1
    op = Tk()
    op.title("ÖĞRENCİ KAYIT")
    #op.configure(background="darkblue")
    op.geometry("600x600")
    ek = Entry(op)
    ek.place(relx=0.7, rely=0.15)
    es = Entry(op)
    es.place(relx=0.7, rely=0.25)
    ew = Entry(op)
    ew.place(relx=0.7, rely=0.35)
    ez = Entry(op)
    ez.place(relx=0.7, rely=0.45)
    ex = Entry(op)
    ex.place(relx=0.7, rely=0.55)

    lo1 = Label(op, text="AD:")
    lo1.place(relx=0.2, rely=0.15)
    lo2 = Label(op, text="SOYAD:")
    lo2.place(relx=0.2, rely=0.25)
    lo3 = Label(op, text="SINIF:")
    lo3.place(relx=0.2, rely=0.35)
    lo4 = Label(op, text="NO:")
    lo4.place(relx=0.2, rely=0.45)
    lo5 = Label(op, text="MEZUN TARİHİ:")
    lo5.place(relx=0.2, rely=0.55)
    b1 = Button(op, text="KAYDET", command=kayit)
    b1.place(relx=0.45, rely=0.6)
    men = Menu(op)
    op.config(menu=men)
    mendosya = Menu(men, tearoff=0)
    men.add_cascade(label='menü', menu=mendosya)
    mendosya.add_command(label="-> ANASAYFAYA DÖN", command=ogeri)
    mendosya.add_command(label="GERİ",command=mogr)
    op.mainloop()

def istanbul():
    yp.withdraw()
    global kp, ke1, ke2, ke3, ke4, kl1, kl2, kl3, kb1, kb2, kb3
    kp = Tk()
    kp.title("KİTAP KAYDET")
    kp.geometry("600x600")
    ke1 = Entry(kp)
    ke1.place(relx=0.6, rely=0.1)
    ke2 = Entry(kp)
    ke2.place(relx=0.6, rely=0.2)
    ke3 = Entry(kp)
    ke3.place(relx=0.6, rely=0.3)
    ke4 = Entry(kp)
    ke4.place(relx=0.35, rely=0.5)
    kl1 = Label(kp, text="KİTAP ADI:")
    kl1.place(relx=0.2, rely=0.1)
    kl2 = Label(kp, text="KİTAP NO:")
    kl2.place(relx=0.2, rely=0.2)
    kl3 = Label(kp, text="YAZAR:")
    kl3.place(relx=0.2, rely=0.3)
    kb1 = Button(kp, text="KAYDET", command=kitkayit)
    kb1.place(relx=0.4, rely=0.4)
    kb2 = Button(kp, text="     SİL     ", command=kitsil)
    kb2.place(relx=0.4, rely=0.6)
    kb3 = Button(kp, text="    ARA    ", command=kara)
    kb3.place(relx=0.4, rely=0.7)
    menuo = Menu(kp)
    kp.config(menu=menuo)
    mend = Menu(menuo, tearoff=0)
    menuo.add_cascade(label="Menü", menu=mend)
    mend.add_command(label="-> ANASAYFAYA GERİ DÖN", command=kgeri)
    mend.add_command(label="GERİ", command=boston)
    kp.mainloop()

def mogr():
    op.destroy()
    yp.deiconify()
def mgeri():
    yp.destroy()
    p.deiconify()
def boston():
    kp.destroy()
    yp.deiconify()

e1=Entry()
e1.place(relx=0.7,rely=0.15)
e2=Entry()
e2.place(relx=0.7,rely=0.25)
e3=Entry()
e3.place(relx=0.7,rely=0.35)
e4=Entry()
e4.place(relx=0.7,rely=0.45)
e5=Entry()
e5.place(relx=0.7,rely=0.55)
e6=Entry()
e6.place(relx=0.7,rely=0.65)
e7=Entry()
e7.place(relx=0.7,rely=0.85)
e8=Entry()
e8.place(relx=0.7,rely=0.75)
l1=Label(text="ADINIZ:",font="Times 10 italic",bg="white")
l1.place(relx=0.1,rely=0.15)
l2=Label(text="SOYADINIZ:",font="Times 10 italic",bg="white")
l2.place(relx=0.1, rely=0.25)
l3=Label(text="NUMARANIZ:",font="Times 10 italic",bg="white")
l3.place(relx=0.1, rely=0.35)

l4=Label(text="SINIFINIZ:",font="Times 10 italic",bg="white")
l4.place(relx=0.1, rely=0.45)
l5=Label(text="KİTAPADI:",font="Times 10 italic",bg="white")
l5.place(relx=0.1, rely=0.55)
l6=Label(text="KİTAPNO:",font="Times 10 italic",bg="white")
l6.place(relx=0.1, rely=0.65)
l7=Label(text="YAZAR",font="Times 10 italic",bg="white")
l7.place(relx=0.1,rely=0.75)
l8=Label(text="TARİH(gün/ay/yıl):",font="Times 10 italic",bg="white")
l8.place(relx=0.1,rely=0.85)
entryara=Entry()
entryara.place(relx=0.37,rely=0.7)
b=Button(text="ÖDÜNÇ VER",bg="white",fg="red",command=kaydet)
b.place(relx=0.4,rely=0.8)
z=Button(text="       ARA       ",bg="white",fg="red",command=ara)
z.place(relx=0.4,rely=0.85)
q=Button(text="         SİL       ",bg="white",fg="red",command=sil)
q.place(relx=0.4,rely=0.9)
locale.setlocale(locale.LC_ALL,'turkish')
zaman=datetime.datetime.today()
#time=datetime.datetime.ctime(zaman)
vertarih=datetime.datetime.strftime(zaman,'%Y %m %d')
tarih=datetime.timedelta(days=15)
altarih=zaman+tarih
altarih.strftime('%Y/%m/%d')
#altarih.strftime("%d")
menu=Menu(p)
p.config(menu=menu)
menudosya=Menu(menu,tearoff=0)
menu.add_cascade(label='Menü',menu=menudosya)
menudosya.add_command(label="ÖĞRENCİ KAYIT",command=ogrenciler)
menudosya.add_command(label="KİTAP KAYDET",command=kitp)
menudosya.add_command(label="MEZUN OLANLARI SİL",command=mezun)
menudosya.add_command(label="EXCEL",command=excel)
menudosya.add_command(label="SÜRESİ DOLAN KİTAPLAR",command=excelr)
mainloop()